include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_void_async
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - omit_local_variable_types
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_final

analyzer:
  exclude:
    - '**/*.reflectable.dart'
